#!/bin/bash

cd examples
vagrant up --provider virtualbox
cd ../cli
go build
./cli commands -z ../examples/exampleCommands.json -m ../examples/exampleInfrastructure.json
rm cli
cd examples
vagrant halt
vagrant destroy -f
